// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcc-3RqyvFbLhi6dENWEYzdzdqfuV9WQ',
    appId: '1:496201691827:web:7d1d7aae23fc887bc7b6c6',
    messagingSenderId: '496201691827',
    projectId: 'vehicle1-8cb44',
    authDomain: 'vehicle1-8cb44.firebaseapp.com',
    storageBucket: 'vehicle1-8cb44.appspot.com',
    measurementId: 'G-Q0RZDB5EZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB-dMnWTxrrsIsuwgkB80hRI-qnpNx1Mo',
    appId: '1:496201691827:android:1a1b0cb89aff4086c7b6c6',
    messagingSenderId: '496201691827',
    projectId: 'vehicle1-8cb44',
    storageBucket: 'vehicle1-8cb44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugC40ZPZzrFh-M2EoJgweUKKvfEdny4o',
    appId: '1:496201691827:ios:a4209534a05d1655c7b6c6',
    messagingSenderId: '496201691827',
    projectId: 'vehicle1-8cb44',
    storageBucket: 'vehicle1-8cb44.appspot.com',
    iosBundleId: 'com.example.vehicleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugC40ZPZzrFh-M2EoJgweUKKvfEdny4o',
    appId: '1:496201691827:ios:8a373175552b0aa9c7b6c6',
    messagingSenderId: '496201691827',
    projectId: 'vehicle1-8cb44',
    storageBucket: 'vehicle1-8cb44.appspot.com',
    iosBundleId: 'com.example.vehicleProject.RunnerTests',
  );
}
